{% set version = "1.6" %}

package:
  name: tensap
  version: {{ version }}

source:
  url: https://github.com/anthony-nouy/tensap/archive/v{{ version }}.tar.gz
  sha256: d32356441efcc65ccaab047948f4f398a08d589eddf095f6ea9156a19b56f36f

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - tensorflow >=2

test:
  requires:
    - python {{ python_min }}
  imports:
    - tensap

about:
  home: https://github.com/anthony-nouy/tensap
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Tensor Approximation Package, a Python package for the approximation of functions and tensors

extra:
  recipe-maintainers:
    - jschueller
