{% set version = "1.5" %}

package:
  name: tensap
  version: {{ version }}

source:
  url: https://github.com/anthony-nouy/tensap/archive/v{{ version }}.tar.gz
  sha256: cc8a94928a80140b08f371e622f24b4ad6fdfb909888d2becf9377ec0f03016e

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - tensorflow >=2

test:
  imports:
    - tensap

about:
  home: https://github.com/anthony-nouy/tensap
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Tensor Approximation Package, a Python package for the approximation of functions and tensors

extra:
  recipe-maintainers:
    - jschueller
